# Generated by Django 2.2 on 2020-07-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
