# Generated by Django 2.2 on 2020-07-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comercio', '0002_auto_20200701_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.BooleanField(),
        ),
    ]
